# configuration
remote_theme: mmistakes/minimal-mistakes@4.20.1
minimal_mistakes_skin: default
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

title: Dr SHE Jiajie
subtitle: Joint Postdoctoral Researcher, HKB & GML
description: to be added
url: https://orcid.org/0000-0003-4286-6411
locale: en-US

defaults:
  - scope:
      path: ''
      type: pages
    values:
      title: ''
      layout: single
      classes:
        - wide
        - fullwidth
